name: auto-sync
on:
  push:
    branches:
      - alpha
  workflow_dispatch: # Allows you to run this workflow manually from the Actions tab
jobs:
  auto-sync:
    runs-on: ubuntu-latest
    steps:
      - uses: octokit/request-action@v2.x
        id: get_latest_release
        with:
          route: GET /repos/:repository/pulls
          repository: ${{ github.repository }}
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
      - run: "echo latest release: ${{ fromJson(steps.get_latest_release.outputs.data) }}"    
      - run: "echo latest release: ${{ fromJson(steps.get_latest_release.outputs.data)[0].auto_merge != null }}"
